services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: app-mobilidade-wpp
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://root:password@postgres:5432/mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ../:/usr/src/app

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-mobilidade-wpp
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres--mobilidade-wpp
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
